### PR TITLE
Remove all stats calls.

### PR DESCRIPTION
**Pull request by mijoharas**
We track enqueued et al. separately. Saves us doing 7 + number_of_queues redis calls per enqueue/dequeue.

### CODE REVIEW

**Review by h-lame — APPROVED** [review]
Change looks good to me.  One tiny idea, but maybe it's a non-starter given our replacement  method for doing enqueued tracking - could it be `q.decrement 'enqueued'` instead of `q.measure 'enqueued', size_of_queue`.  Obvs only works if we elsewhere had a corresponding `q.increment 'enqueued'` when things are actually enqueued.

**Comment by mijoharas** [comment]
I actually wondered something similar, but I thought we've got something that works, and didn't want to subtly change some graphs in ways I hadn't thought through, so just decided to ditch the idea. Happy to revisit later if you want :man_shrugging:

**Comment by mijoharas** [comment]
oh, and fyi, this commit is tagged with` v0.2.2`

**Comment by mijoharas** [comment]
whiiiich... reminds me I forgot to bump the `VERSION`

**Comment by mijoharas** [comment]
now it's the latest commit that's v0.2.2

**Comment by h-lame** [comment]
> I actually wondered something similar, but I thought we've got something that works, and didn't want to subtly change some graphs in ways I hadn't thought through, so just decided to ditch the idea. Happy to revisit later if you want 🤷‍♂️

It's a good call, I hadn't thought about the repercussions of turning a `measure` into an `increment`/`decrement` pair.  It'd probably be subtly weird.  I think the alt approach for `enqueued` is probably fine anyway.  Hopefully we don't need to revisit.

**Review by joshuafleck — COMMENTED** [review]
🏩

**Pull request merged**
